A simple infrastructure to run the C++ unit tests.

diff --git a/core/Makefile.sub b/core/Makefile.sub
--- a/core/Makefile.sub
+++ b/core/Makefile.sub
@@ -9,7 +9,12 @@ SOURCES := $(SRC_C) $(SRC_CPP)
 OBJECTS := $(addprefix $(BUILDDIR)/, $(SRC_C:.c=$(OBJEXT)) $(SRC_CPP:.cpp=$(OBJEXT)))
 DEPENDS := $(addprefix $(BUILDDIR)/, $(SRC_C:.c=.d) $(SRC_CPP:.cpp=.d))
 
-.PHONY: all depend clean clobber
+# for tests
+T_SRC_CPP := $(wildcard test/t_*.cpp)
+T_BINS := $(patsubst test/%, test/$(BUILDDIR)/%, $(T_SRC_C:.c=$(BINEXT)) $(T_SRC_CPP:.cpp=$(BINOBJEXT)))
+T_DEPENDS := $(patsubst test/%, test/$(BUILDDIR)/%, $(T_SRC_C:.c=.d) $(T_SRC_CPP:.cpp=.d))
+
+.PHONY: all depend clean clobber mktest test qtest vtest
 
 ifeq (,$(strip $(NODEP) $(filter help% clean% %clean clobber%, $(MAKECMDGOALS))))
 -include $(DEPENDS)
@@ -29,7 +34,7 @@ $(BUILDDIR)/%$(OBJEXT): %.cpp Makefile ../Makefile.inc
 $(BUILDDIR)/%$(OBJEXT): %.c Makefile ../Makefile.inc
 	$(CC) $(CFLAGS) -c -o $@ $<
 
-depend: $(DEPENDS)
+depend: $(DEPENDS) $(T_DEPENDS)
 
 $(BUILDDIR)/%.d: %.cpp Makefile ../Makefile.inc
 	rm -f $@; \
@@ -43,12 +48,63 @@ $(BUILDDIR)/%.d: %.c Makefile ../Makefile.inc
 	sed 's,\($*\)\.o[ :]*,$(BUILDDIR)/\1.o $@ : ,g' < $@.$$$$ > $@ && \
 	rm -f $@.$$$$
 
-clean:
-	rm -rf $(BUILDDIR)
+cleancore:
+	rm -f core.* *.core core vgcore.*
+
+clean: cleancore
+	rm -rf $(BUILDDIR) test/$(BUILDDIR) 
 
 clobber:
 	rm -f $(OBJECTS) $(DEPENDS)
 
 cleandep:
 	rm -f $(DEPENDS)
+
+### the test stuff ###
+
+mktest: $(T_BINS)
+
+test: vtest
+
+# quick test, without valgrind
+qtest: cleancore mktest
+	@echo "Unit tests:"; for i in  $(T_BINS); do \
+		basename $$i; $$i || { echo "  FAIL" >&2; exit 1; } \
+	done
+
+# detailed test, with valgrind
+vtest: cleancore mktest
+	@echo "Unit tests valgrind:"; for i in  $(T_BINS); do \
+		basename $$i; $(VALGRIND) $$i >$$i.vg 2>&1  || { echo "  FAIL" >&2; exit 1; }; \
+		grep "ERROR SUMMARY: .*[^0].* errors from" $$i.vg && { echo "  FAIL MEMCHK" >&2; exit 1; }; \
+		grep "are definitely lost" $$i.vg && { echo "  FAIL LEAK" >&2; exit 1; }; \
+	done; true
+
+$(T_DEPENDS): | test/$(BUILDDIR)
+
+$(T_BINS): | test/$(BUILDDIR)
+
+test/$(BUILDDIR):
+	mkdir test/$(BUILDDIR)
+	echo "$(T_SRC_CPP)"
+	echo "$(T_DEPENDS)"
+	echo "$(T_BINS)"
+
+test/$(BUILDDIR)/%.d: test/%.cpp Makefile ../Makefile.inc
+	rm -f $@; \
+	$(CXX) -M $(CPPFLAGS) $< > $@.$$$$ && \
+	sed 's,\($*\)\.o[ :]*,$(BUILDDIR)/\1.o $@ : ,g' < $@.$$$$ > $@ && \
+	rm -f $@.$$$$
+
+test/$(BUILDDIR)/%.d: test/%.c Makefile ../Makefile.inc
+	rm -f $@; \
+	$(CC) -M $(CPPFLAGS) $< > $@.$$$$ && \
+	sed 's,\($*\)\.o[ :]*,$(BUILDDIR)/\1.o $@ : ,g' < $@.$$$$ > $@ && \
+	rm -f $@.$$$$
+
+test/$(BUILDDIR)/%$(BINEXT): test/%.cpp Makefile ../Makefile.inc
+	$(CXX) $(CXXFLAGS) $(TESTLDFLAGS) -o $@ $<
+
+test/$(BUILDDIR)/%$(BINEXT): test/%.c Makefile ../Makefile.inc
+	$(CC) $(CFLAGS) $(TESTLDFLAGS) -o $@ $<
 
